# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Wed, 02 May 2018 11:19:32 +0000
*               @ALL          1
*               @user         8