<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Wed, 02 May 2018 19:24:28 +0800
 */

$conf['title'] = 'doku';
$conf['start'] = 'start';
$conf['lang'] = 'zh';
$conf['license'] = 'cc-by-sa';
$conf['breadcrumbs'] = 0;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['userewrite'] = '1';
$conf['useslash'] = 1;
$conf['plugin']['authmysql']['TablesToLock'] = array();

// end auto-generated content